baseURL = "https://birthwithiraivi.com/"
languageCode = 'en-us'
title = 'Iraivi | Celebrating Motherhood'
theme = 'iraivi-hugo-theme'

[[menu.main]]
name = "Home"
url = "/"
weight = 10
identifier = "home"
[menu.main.params]
show = true

[[menu.main]]
name = "Gayathri"
url = "/about-me/"
weight = 20
identifier = "about"
[menu.main.params]
show = true

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 30
identifier = "blog"
[menu.main.params]
show = false

[[menu.main]]
name = "Courses"
url = "/courses/"
weight = 40
identifier = "courses"
[menu.main.params]
show = true

[[menu.main]]
name = "Lactation Consultation"
url = "/lactation-consultation/"
weight = 50
identifier = "lactation"
[menu.main.params]
show = true

[[menu.main]]
name = "FAQ"
url = "/#faq"
weight = 60
identifier = "faq"
[menu.main.params]
show = true

[[menu.main]]
name = "Enquiry"
url = "/enquiry/"
weight = 70
identifier = "enquiry"
[menu.main.params]
show = true
variant = "button"


#################### default parameters ################################
[params]
logo = "images/Iraivi_logo-1.png"
og_image = "images/iraivi-icon.jpg"
home = "Home"
phone = "7550114682"
whatsapp = "917550114682"
email = "iraivipregcare@gmail.com"
instagram = "https://www.instagram.com/iraivipregnancycare/"
tensketch_url = "~"
# Meta data
description = "I’m Gayathri Suresh, a childbirth educator. Iraivi is here to assist with the transition, laying the groundwork for confident childbirth and parenthood."
keywords = "childbirth, pregnancy, pregancy care, how to get a normal delivery, normal delivery videos, birthcare, normal delivery, childbirth educator, Pregnancy nutrition, Prenatal bonding, Labor and birth, Pre and postnatal fitness, Breastfeeding, Newborn care, Postpartum care, Lactation Counselling, parenting"
author = "TenSketch"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/css/main.css"
  
  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/js/main.js"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
