baseURL = "https://iraivi.netlify.app/"
languageCode = 'en-us'
title = 'Iraivi | Celebrating Mothehood'
theme = 'iraivi-hugo-theme'

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/css/main.css"
  
  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/js/main.js"